export const experian = {
  "Fico Score": "816",
  "Open accounts": "16",
  "Average account age": "9 yrs 4 mos",
  "Credit used": "109062",
  "Credit limit": "192040",
  "Utilization %": "57%",
  "Total Inquiries": 1,
  "Inquiries 3 mos": 0,
  "Inquiries 6 mos": 1,
  "Account info": [
    {
      "Account Name": "APPLE CARD GS BANK USA",
      "Account Type": "Credit card",
      "Account Status": "Open Never late",
      "Reporting Date": "31",
      "Date Opened": "Apr 23, 2023",
      "Current Balance": "1070",
      "Account Limit": "10000",
      "Account Utilization": 11,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "BEST BUY CBNA",
      "Account Type": "Charge Card",
      "Account Status": "Open Never late",
      "Reporting Date": "30",
      "Date Opened": "Mar 16, 2012",
      "Current Balance": "79",
      "Account Limit": "3500",
      "Account Utilization": 2,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "BEST EGG",
      "Account Type": "Unsecured",
      "Account Status": "Open Never late",
      "Reporting Date": "31",
      "Date Opened": "Mar 07, 2022",
      "Current Balance": "3680",
      "Account Limit": "40000",
      "Account Utilization": 9,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "CAPITAL ONE",
      "Account Type": "Credit card",
      "Account Status": "Open Never late",
      "Reporting Date": "14",
      "Date Opened": "May 01, 2014",
      "Current Balance": "1763",
      "Account Limit": "8000",
      "Account Utilization": 22,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "CAPITAL ONE",
      "Account Type": "Credit card",
      "Account Status": "Open Never late",
      "Reporting Date": "26",
      "Date Opened": "Feb 18, 2004",
      "Current Balance": "297",
      "Account Limit": "11600",
      "Account Utilization": 3,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "CITICARDS CBNA",
      "Account Type": "Credit card",
      "Account Status": "Open Never late",
      "Reporting Date": "14",
      "Date Opened": "Jun 04, 2016",
      "Current Balance": "555",
      "Account Limit": "9500",
      "Account Utilization": 6,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "DISCOVER BANK",
      "Account Type": "Credit card",
      "Account Status": "Open Never late",
      "Reporting Date": "26",
      "Date Opened": "May 08, 2021",
      "Current Balance": "0",
      "Account Limit": "8000",
      "Account Utilization": 0,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "DISCOVER BANK",
      "Account Type": "Credit card",
      "Account Status": "Open Never late",
      "Reporting Date": "17",
      "Date Opened": "Aug 28, 2014",
      "Current Balance": "2804",
      "Account Limit": "12000",
      "Account Utilization": 23,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "FIGURE LENDING FIGURE",
      "Account Type": "Home Equity",
      "Account Status": "Open Never late",
      "Reporting Date": "25",
      "Date Opened": "Sep 10, 2024",
      "Current Balance": "100331",
      "Account Limit": "101990",
      "Account Utilization": 98,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "FNB OMAHA",
      "Account Type": "Credit card",
      "Account Status": "Open Never late",
      "Reporting Date": "28",
      "Date Opened": "Aug 01, 2013",
      "Current Balance": "1045",
      "Account Limit": "9450",
      "Account Utilization": 11,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "LENDING CLUB CORP",
      "Account Type": "Unsecured",
      "Account Status": "Open Never late",
      "Reporting Date": "31",
      "Date Opened": "May 01, 2024",
      "Current Balance": "29166",
      "Account Limit": "35000",
      "Account Utilization": 83,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "NATIONSTAR MR COOPER",
      "Account Type": "Mortgage",
      "Account Status": "Open Never late",
      "Reporting Date": "31",
      "Date Opened": "Jun 04, 2020",
      "Current Balance": "229911",
      "Account Limit": "279600",
      "Account Utilization": 82,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "NEW AMERICAN FUNDING",
      "Account Type": "Mortgage",
      "Account Status": "Open Never late",
      "Reporting Date": "06",
      "Date Opened": "Dec 23, 2020",
      "Current Balance": "41297",
      "Account Limit": "59500",
      "Account Utilization": 69,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "TD BANK NA",
      "Account Type": "Credit card",
      "Account Status": "Open Never late",
      "Reporting Date": "25",
      "Date Opened": "Mar 30, 2016",
      "Current Balance": "1118",
      "Account Limit": "18000",
      "Account Utilization": 6,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "TRENTON NJ FIREMEN FCU",
      "Account Type": "Auto Loan",
      "Account Status": "Open Never late",
      "Reporting Date": "31",
      "Date Opened": "Aug 30, 2022",
      "Current Balance": "3558",
      "Account Limit": "15884",
      "Account Utilization": 22,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "UNITED CONSUMER FINL S",
      "Account Type": "Sales Contract",
      "Account Status": "Open Never late",
      "Reporting Date": "11",
      "Date Opened": "Mar 15, 2024",
      "Current Balance": "5790",
      "Account Limit": "8116",
      "Account Utilization": 71,
      "Account Responsibility": "Individual",
    },
  ],
  "Inquiries Info": [
    {
      "Bank Name": "MOVEMENT MORTGAGE FIGU",
      "Inquiry Date": "Sep 6, 2024",
      "Removal Date": "Oct 2026",
    },
  ],
};

export const transunion = {
  "Fico Score": "554",
  "Open accounts": "5",
  "Average account age": "4 yrs",
  "Credit used": "748",
  "Credit limit": "1600",
  "Utilization %": "47%",
  "Total Inquiries": 6,
  "Inquiries 3 mos": 0,
  "Inquiries 6 mos": 1,
  "Account info": [
    {
      "Account Name": "CAPITAL ONE",
      "Account Type": "Revolving account ",
      "Account Status": "Paid or paying as agreed",
      "Reporting Date": "23",
      "Date Opened": "Mar 20, 2024",
      "Current Balance": "54",
      "Account Limit": "300",
      "Account Utilization": 18,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "CAPITAL ONE",
      "Account Type": "Revolving account ",
      "Account Status": "Paid or paying as agreed",
      "Reporting Date": "23",
      "Date Opened": "Jun 24, 2024",
      "Current Balance": "290",
      "Account Limit": "300",
      "Account Utilization": 97,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "CB INDIGO",
      "Account Type": "Revolving account ",
      "Account Status": "Paid or paying as agreed",
      "Reporting Date": "20",
      "Date Opened": "Sep 03, 2024",
      "Current Balance": "0",
      "Account Limit": "500",
      "Account Utilization": 0,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "FLEX",
      "Account Type": "Open account",
      "Account Status": "Paid or paying as agreed",
      "Reporting Date": "01",
      "Date Opened": "Jul 01, 2024",
      "Current Balance": "0",
      "Account Limit": "994",
      "Account Utilization": 0,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "TBOM MILSTNE",
      "Account Type": "Revolving account ",
      "Account Status": "Paid or paying as agreed",
      "Reporting Date": "16",
      "Date Opened": "Jun 28, 2024",
      "Current Balance": "404",
      "Account Limit": "500",
      "Account Utilization": 81,
      "Account Responsibility": "Individual",
    },
  ],
  "Inquiries Info": [
    {
      "Bank Name": "CAPITAL ONE",
      "Inquiry Date": "Jun 24, 2024",
      "Removal Date": "Jul 2026",
    },
    {
      "Bank Name": "CAPITAL ONE",
      "Inquiry Date": "Mar 4, 2024",
      "Removal Date": "Apr 2026",
    },
    {
      "Bank Name": "CAPITAL ONE",
      "Inquiry Date": "Oct 3, 2023",
      "Removal Date": "Nov 2025",
    },
    {
      "Bank Name": "CB INDIGO",
      "Inquiry Date": "Sep 3, 2024",
      "Removal Date": "Oct 2026",
    },
    {
      "Bank Name": "CHECKNGOAXF",
      "Inquiry Date": "Nov 15, 2022",
      "Removal Date": "Dec 2024",
    },
    {
      "Bank Name": "TBOM MILESTO",
      "Inquiry Date": "Jun 28, 2024",
      "Removal Date": "Jul 2026",
    },
  ],
};

export const equifax = {
  "Fico Score": "545",
  "Open accounts": "4",
  "Average account age": "4 yrs 3 mos",
  "Credit used": "748",
  "Credit limit": "1600",
  "Utilization %": "47%",
  "Total Inquiries": 3,
  "Inquiries 3 mos": 0,
  "Inquiries 6 mos": 0,
  "Account info": [
    {
      "Account Name": "CAPITAL ONE BANK USA",
      "Account Type": "Revolving Status",
      "Account Status": "Pays account as agreed",
      "Reporting Date": "23",
      "Date Opened": "Mar 20, 2024",
      "Current Balance": "54",
      "Account Limit": "300",
      "Account Utilization": 18,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "CAPITAL ONE BANK USA",
      "Account Type": "Revolving Status",
      "Account Status": "Pays account as agreed",
      "Reporting Date": "23",
      "Date Opened": "Jun 24, 2024",
      "Current Balance": "290",
      "Account Limit": "300",
      "Account Utilization": 97,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "CB INDIGO",
      "Account Type": "Revolving Status",
      "Account Status": "Pays account as agreed",
      "Reporting Date": "20",
      "Date Opened": "Sep 03, 2024",
      "Current Balance": "0",
      "Account Limit": "500",
      "Account Utilization": 0,
      "Account Responsibility": "Individual",
    },
    {
      "Account Name": "TBOM MIL",
      "Account Type": "Revolving Status",
      "Account Status": "Pays account as agreed",
      "Reporting Date": "16",
      "Date Opened": "Jun 28, 2024",
      "Current Balance": "404",
      "Account Limit": "500",
      "Account Utilization": 81,
      "Account Responsibility": "Individual",
    },
  ],
  "Inquiries Info": [
    {
      "Bank Name": "CAPITAL ONE BANK USA",
      "Inquiry Date": "Jun 24, 2024",
      "Removal Date": "Jul 2026",
    },
    {
      "Bank Name": "CAPITAL ONE BANK USA",
      "Inquiry Date": "Mar 4, 2024",
      "Removal Date": "Apr 2026",
    },
    {
      "Bank Name": "CAPITAL ONE BANK USA",
      "Inquiry Date": "Oct 3, 2023",
      "Removal Date": "Nov 2025",
    },
  ],
};
